image: registry.sensetime.com/eig-research/pytorch:1.3.1-cuda10.1-cudnn7-devel

stages:
    - linting
    - test

before_script:
  - echo $PATH
  - gcc --version
  - nvcc --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"

linting:
  stage: linting
  script:
    - pip install flake8 yapf isort
    - flake8 .
    - isort -rc --check-only --diff mmcv/ tests/
    - yapf -r -d mmcv/ tests/

test:
  stage: test
  script:
    - echo "Start building..."
    - pip install PyTurboJPEG lmdb pillow==6.2.2 pytest coverage
    - pip install -e .
    - python -c "import mmcv; print(mmcv.__version__)"
    - echo "Start testing..."
    - coverage run --branch --source mmcv -m pytest tests/
    - coverage report -m
